version: '3.8'

services:
  mongo:
    image: mongo:7
    container_name: shellfusion-mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: appdb
    volumes:
      - mongo_data:/data/db
      - ./mongo-init:/docker-entrypoint-initdb.d:ro
    networks:
      - shellfusion-network

volumes:
  mongo_data:
    driver: local

networks:
  shellfusion-network:
    driver: bridge